#### 15-03-2022

In [ ]:
from keras.preprocessing.text import Tokenizer

In [ ]:
t = Tokenizer()
#Defining 4 document lists
fit_text = ['Machine Learning Knowledge',
            'Deep Learning',
            'Machine Learning',
            'Artificial intelligence']
t.fit_on_texts(fit_text)

In [ ]:
# The documnet_count rints the no. of documnets present in our corpus
print("The documnet count:", t.document_count)

The documnet count: 4


In [ ]:
# The word_count shows the no. of times words occur in the text corpus
print("The words count:", t.word_counts)

The words count: OrderedDict([('machine', 2), ('learning', 3), ('knowledge', 1), ('deep', 1), ('artificial', 1), ('intelligence', 1)])


In [ ]:
#Assigns a unique index to each word present in the text
print("The words index:", t.word_index)

The words index: {'learning': 1, 'machine': 2, 'knowledge': 3, 'deep': 4, 'artificial': 5, 'intelligence': 6}


In [ ]:
#Tells in how many documents each of the word appear
print("The word docs:", t.word_docs)

The word docs: defaultdict(<class 'int'>, {'machine': 2, 'learning': 3, 'knowledge': 1, 'deep': 1, 'artificial': 1, 'intelligence': 1})


In [ ]:
t = Tokenizer()
fit_text = "Machine Learning"

t.fit_on_texts(fit_text)

print("Count of characters", t.word_counts)
print("Length f text", t.document_count)
print("Character index", t.word_index)
print("FRequency of characters",t.word_docs )

Count of characters OrderedDict([('m', 1), ('a', 2), ('c', 1), ('h', 1), ('i', 2), ('n', 3), ('e', 2), ('l', 1), ('r', 1), ('g', 1)])
Length f text 16
Character index {'n': 1, 'a': 2, 'i': 3, 'e': 4, 'm': 5, 'c': 6, 'h': 7, 'l': 8, 'r': 9, 'g': 10}
FRequency of characters defaultdict(<class 'int'>, {'m': 1, 'a': 2, 'c': 1, 'h': 1, 'i': 2, 'n': 3, 'e': 2, 'l': 1, 'r': 1, 'g': 1})


In [ ]:
# Text to sequence:  convert to numbers 

In [ ]:
t = Tokenizer()
test_text = ['Machine Learning Knowledge',
            'Deep Learning',
            'Machine Learning',
            'Artificial intelligence']
t.fit_on_texts(test_text)
sequences = t.texts_to_sequences(test_text)
print("The sequences generated from the text are ", sequences)

The sequences generated from the text are  [[2, 1, 3], [4, 1], [2, 1], [5, 6]]


text to sequence on a string

In [ ]:
t = Tokenizer()
test_text = 'Machine Learning'
t.fit_on_texts(test_text)
sequences = t.texts_to_sequences(test_text)
print("The sequences generated from the text are ", sequences)

The sequences generated from the text are  [[5], [2], [6], [7], [3], [1], [4], [], [8], [4], [2], [9], [1], [3], [1], [10]]


text to matrix

In [ ]:
docs = ['Marvellous machine learning',
        'Dazzling deep learning',
        'Champion computer vision']
t = Tokenizer()
t.fit_on_texts(docs)
encoded_docs = t.texts_to_matrix(docs, mode='binary')
print(encoded_docs)

[[0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1.]]


In [ ]:
docs = ['Marvellous machine learning Marvellous machine learning',
        'Dazzling deep learning',
        'Champion computer vision']
t = Tokenizer()
t.fit_on_texts(docs)
encoded_docs = t.texts_to_matrix(docs, mode='count')
print(encoded_docs)

[[0. 2. 2. 2. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1.]]


TEXTS TO MATRIX WITH MODE = tfidf

In [ ]:
docs = ['Marvellous machine learning Marvellous machine learning',
        'Dazzling deep learning',
        'Champion computer vision']
t = Tokenizer()
t.fit_on_texts(docs)
encoded_docs = t.texts_to_matrix(docs, mode='tfidf')
print(encoded_docs)

[[0.         1.17360019 1.55141507 1.55141507 0.         0.
  0.         0.         0.        ]
 [0.         0.69314718 0.         0.         0.91629073 0.91629073
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.91629073 0.91629073 0.91629073]]


TEXTS TO MATRIX WITH MODE = freq

In [ ]:
docs = ['Marvellous machine learning Marvellous machine learning',
        'Dazzling deep learning',
        'Champion computer vision']
t = Tokenizer()
t.fit_on_texts(docs)
encoded_docs = t.texts_to_matrix(docs, mode='freq')
print(encoded_docs)

[[0.         0.33333333 0.33333333 0.33333333 0.         0.
  0.         0.         0.        ]
 [0.         0.33333333 0.         0.         0.33333333 0.33333333
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.33333333 0.33333333 0.33333333]]


#### 15-03-2022 Lab Session

In [ ]:
import keras
import numpy as np
from keras.datasets import reuters
import tensorflow as tf

In [ ]:
(x_train, y_train), (x_test, y_test) = reuters.load_data(num_words=None, test_split=0.2)

2121728/2110848 [==============================] - 0s 0us/step


In [ ]:
print(len(x_train))
print(len(x_test))

8982
2246


In [ ]:
num_classes  = max(y_train)+1
print(num_classes)

46


In [ ]:
from keras.preprocessing.text import Tokenizer

max_words = 10000

In [ ]:
tokenizer = Tokenizer(num_words=max_words)
x_train = tokenizer.sequences_to_matrix(x_train, mode='binary')
x_test = tokenizer.sequences_to_matrix(x_test, mode='binary')

In [ ]:
y_train  = tf.keras.utils.to_categorical(y_train, num_classes)
y_test  = tf.keras.utils.to_categorical(y_test, num_classes)

In [ ]:
print(x_train[0])
print(len(x_train[0]))
print(max(x_train[0]))

[0. 1. 0. ... 0. 0. 0.]
10000
1.0


In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation

In [ ]:
model = Sequential()
model.add(Dense(512, input_shape=(max_words,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer = 'adam',metrics = ['accuracy'])

In [ ]:
batch_size = 32
epochs=10

In [ ]:
history = model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, validation_split=0.1)
score= model.evaluate(x_test, y_test, batch_size=batch_size, verbose=1)
print('Test loss: ', score[0])
print('Test accuracy: ',score[1])

Epoch 1/10
253/253 [==============================] - 8s 32ms/step - loss: 0.1671 - accuracy: 0.9587 - val_loss: 0.6376 - val_accuracy: 0.8721
Epoch 2/10
253/253 [==============================] - 8s 32ms/step - loss: 0.1755 - accuracy: 0.9608 - val_loss: 0.6579 - val_accuracy: 0.8710
Epoch 3/10
253/253 [==============================] - 8s 31ms/step - loss: 0.1625 - accuracy: 0.9581 - val_loss: 0.6529 - val_accuracy: 0.8665
Epoch 4/10
253/253 [==============================] - 8s 32ms/step - loss: 0.1683 - accuracy: 0.9597 - val_loss: 0.6685 - val_accuracy: 0.8732
Epoch 5/10
253/253 [==============================] - 8s 32ms/step - loss: 0.1725 - accuracy: 0.9581 - val_loss: 0.7031 - val_accuracy: 0.8665
Epoch 6/10
253/253 [==============================] - 8s 32ms/step - loss: 0.1871 - accuracy: 0.9588 - val_loss: 0.7037 - val_accuracy: 0.8654
Epoch 7/10
253/253 [==============================] - 8s 32ms/step - loss: 0.1598 - accuracy: 0.9600 - val_loss: 0.7675 - val_accuracy: 0.8598

mode= count

In [ ]:
(x_train, y_train), (x_test, y_test) = reuters.load_data(num_words=None, test_split=0.2)

In [ ]:
print(len(x_train))
print(len(x_test))

8982
2246


In [ ]:
num_classes  = max(y_train)+1
print(num_classes)

46


In [ ]:
from keras.preprocessing.text import Tokenizer

max_words = 10000

In [ ]:
tokenizer = Tokenizer(num_words=max_words)
x_train = tokenizer.sequences_to_matrix(x_train, mode='count')
x_test = tokenizer.sequences_to_matrix(x_test, mode='count')

In [ ]:
y_train  = tf.keras.utils.to_categorical(y_train, num_classes)
y_test  = tf.keras.utils.to_categorical(y_test, num_classes)

In [ ]:
print(x_train[0])
print(len(x_train[0]))
print(max(x_train[0]))

[0. 1. 0. ... 0. 0. 0.]
10000
6.0


In [ ]:
model = Sequential()
model.add(Dense(512, input_shape=(max_words,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer = 'adam',metrics = ['accuracy'])

In [ ]:
batch_size = 32
epochs=10

In [ ]:
history = model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, validation_split=0.1)
score= model.evaluate(x_test, y_test, batch_size=batch_size, verbose=1)
print('Test loss: ', score[0])
print('Test accuracy: ',score[1])

Epoch 1/10
253/253 [==============================] - 9s 34ms/step - loss: 1.3190 - accuracy: 0.7268 - val_loss: 0.9700 - val_accuracy: 0.8076
Epoch 2/10
253/253 [==============================] - 8s 31ms/step - loss: 0.5651 - accuracy: 0.8768 - val_loss: 0.8869 - val_accuracy: 0.8320
Epoch 3/10
253/253 [==============================] - 8s 31ms/step - loss: 0.3396 - accuracy: 0.9239 - val_loss: 0.9255 - val_accuracy: 0.8220
Epoch 4/10
253/253 [==============================] - 8s 31ms/step - loss: 0.2657 - accuracy: 0.9393 - val_loss: 0.9710 - val_accuracy: 0.8209
Epoch 5/10
253/253 [==============================] - 9s 36ms/step - loss: 0.2393 - accuracy: 0.9478 - val_loss: 1.0259 - val_accuracy: 0.8076
Epoch 6/10
253/253 [==============================] - 8s 33ms/step - loss: 0.2303 - accuracy: 0.9480 - val_loss: 1.0559 - val_accuracy: 0.8031
Epoch 7/10
253/253 [==============================] - 9s 36ms/step - loss: 0.2071 - accuracy: 0.9537 - val_loss: 1.1310 - val_accuracy: 0.8076

mode= freq

In [ ]:
(x_train, y_train), (x_test, y_test) = reuters.load_data(num_words=None, test_split=0.2)

In [ ]:
print(len(x_train))
print(len(x_test))

8982
2246


In [ ]:
num_classes  = max(y_train)+1
print(num_classes)

46


In [ ]:
from keras.preprocessing.text import Tokenizer

max_words = 10000

In [ ]:
tokenizer = Tokenizer(num_words=max_words)
x_train = tokenizer.sequences_to_matrix(x_train, mode='freq')
x_test = tokenizer.sequences_to_matrix(x_test, mode='freq')

In [ ]:
y_train  = tf.keras.utils.to_categorical(y_train, num_classes)
y_test  = tf.keras.utils.to_categorical(y_test, num_classes)

In [ ]:
print(x_train[0])
print(len(x_train[0]))
print(max(x_train[0]))

[0.         0.01149425 0.         ... 0.         0.         0.        ]
10000
0.06896551724137931


In [ ]:
model = Sequential()
model.add(Dense(512, input_shape=(max_words,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer = 'adam',metrics = ['accuracy'])

In [ ]:
batch_size = 32
epochs=10

In [ ]:
history = model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, validation_split=0.1)
score= model.evaluate(x_test, y_test, batch_size=batch_size, verbose=1)
print('Test loss: ', score[0])
print('Test accuracy: ',score[1])

Epoch 1/10
253/253 [==============================] - 9s 36ms/step - loss: 2.3339 - accuracy: 0.4407 - val_loss: 1.9165 - val_accuracy: 0.5006
Epoch 2/10
253/253 [==============================] - 9s 35ms/step - loss: 1.7323 - accuracy: 0.5479 - val_loss: 1.6483 - val_accuracy: 0.6162
Epoch 3/10
253/253 [==============================] - 8s 31ms/step - loss: 1.4921 - accuracy: 0.6580 - val_loss: 1.4602 - val_accuracy: 0.6952
Epoch 4/10
253/253 [==============================] - 8s 31ms/step - loss: 1.3111 - accuracy: 0.7048 - val_loss: 1.3288 - val_accuracy: 0.7086
Epoch 5/10
253/253 [==============================] - 8s 33ms/step - loss: 1.1659 - accuracy: 0.7262 - val_loss: 1.2310 - val_accuracy: 0.7197
Epoch 6/10
253/253 [==============================] - 8s 32ms/step - loss: 1.0492 - accuracy: 0.7544 - val_loss: 1.1587 - val_accuracy: 0.7397
Epoch 7/10
253/253 [==============================] - 8s 31ms/step - loss: 0.9507 - accuracy: 0.7840 - val_loss: 1.1004 - val_accuracy: 0.7508

mode = tfidf

In [ ]:
(x_train, y_train), (x_test, y_test) = reuters.load_data(num_words=None, test_split=0.2)

In [ ]:
print(len(x_train))
print(len(x_test))

8982
2246


In [ ]:
num_classes  = max(y_train)+1
print(num_classes)

46


In [ ]:
from keras.preprocessing.text import Tokenizer

max_words = 10000

In [ ]:
tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_sequences(x_train)
x_train = tokenizer.sequences_to_matrix(x_train, mode='tfidf')
x_test = tokenizer.sequences_to_matrix(x_test, mode='tfidf')

In [ ]:
y_train  = tf.keras.utils.to_categorical(y_train, num_classes)
y_test  = tf.keras.utils.to_categorical(y_test, num_classes)

In [ ]:
print(x_train[0])
print(len(x_train[0]))
print(max(x_train[0]))

[0.         0.69309152 0.         ... 0.         0.         0.        ]
10000
6.214608098422191


In [ ]:
model = Sequential()
model.add(Dense(512, input_shape=(max_words,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer = 'adam',metrics = ['accuracy'])

In [ ]:
batch_size = 32
epochs=10

In [ ]:
history = model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, validation_split=0.1)
score= model.evaluate(x_test, y_test, batch_size=batch_size, verbose=1)
print('Test loss: ', score[0])
print('Test accuracy: ',score[1])

Epoch 1/10
253/253 [==============================] - 8s 32ms/step - loss: 1.2482 - accuracy: 0.7515 - val_loss: 0.9282 - val_accuracy: 0.8276
Epoch 2/10
253/253 [==============================] - 8s 31ms/step - loss: 0.4316 - accuracy: 0.9135 - val_loss: 1.0230 - val_accuracy: 0.8120
Epoch 3/10
253/253 [==============================] - 8s 31ms/step - loss: 0.3168 - accuracy: 0.9446 - val_loss: 1.0962 - val_accuracy: 0.8042
Epoch 4/10
253/253 [==============================] - 8s 31ms/step - loss: 0.3132 - accuracy: 0.9521 - val_loss: 1.2915 - val_accuracy: 0.7887
Epoch 5/10
253/253 [==============================] - 8s 31ms/step - loss: 0.3022 - accuracy: 0.9562 - val_loss: 1.3058 - val_accuracy: 0.7964
Epoch 6/10
253/253 [==============================] - 8s 31ms/step - loss: 0.3003 - accuracy: 0.9543 - val_loss: 1.3437 - val_accuracy: 0.7953
Epoch 7/10
253/253 [==============================] - 8s 31ms/step - loss: 0.3122 - accuracy: 0.9511 - val_loss: 1.3901 - val_accuracy: 0.7909

#### Real time data

In [ ]:
import keras
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/NLP/IMDB Dataset.csv")
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
(x_train, y_train), (x_test, y_test) = reuters.load_data(num_words=None, test_split=0.2)

2121728/2110848 [==============================] - 0s 0us/step


In [ ]:
print(len(x_train))
print(len(x_test))

8982
2246


In [ ]:
num_classes  = max(y_train)+1
print(num_classes)

46


In [ ]:
from keras.preprocessing.text import Tokenizer

max_words = 10000

In [ ]:
tokenizer = Tokenizer(num_words=max_words)
x_train = tokenizer.sequences_to_matrix(x_train, mode='binary')
x_test = tokenizer.sequences_to_matrix(x_test, mode='binary')

In [ ]:
y_train  = tf.keras.utils.to_categorical(y_train, num_classes)
y_test  = tf.keras.utils.to_categorical(y_test, num_classes)

In [ ]:
print(x_train[0])
print(len(x_train[0]))
print(max(x_train[0]))

[0. 1. 0. ... 0. 0. 0.]
10000
1.0


In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation

In [ ]:
model = Sequential()
model.add(Dense(512, input_shape=(max_words,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer = 'adam',metrics = ['accuracy'])

In [ ]:
batch_size = 32
epochs=10

In [ ]:
history = model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, validation_split=0.1)
score= model.evaluate(x_test, y_test, batch_size=batch_size, verbose=1)
print('Test loss: ', score[0])
print('Test accuracy: ',score[1])

Epoch 1/10
253/253 [==============================] - 8s 32ms/step - loss: 0.1671 - accuracy: 0.9587 - val_loss: 0.6376 - val_accuracy: 0.8721
Epoch 2/10
253/253 [==============================] - 8s 32ms/step - loss: 0.1755 - accuracy: 0.9608 - val_loss: 0.6579 - val_accuracy: 0.8710
Epoch 3/10
253/253 [==============================] - 8s 31ms/step - loss: 0.1625 - accuracy: 0.9581 - val_loss: 0.6529 - val_accuracy: 0.8665
Epoch 4/10
253/253 [==============================] - 8s 32ms/step - loss: 0.1683 - accuracy: 0.9597 - val_loss: 0.6685 - val_accuracy: 0.8732
Epoch 5/10
253/253 [==============================] - 8s 32ms/step - loss: 0.1725 - accuracy: 0.9581 - val_loss: 0.7031 - val_accuracy: 0.8665
Epoch 6/10
253/253 [==============================] - 8s 32ms/step - loss: 0.1871 - accuracy: 0.9588 - val_loss: 0.7037 - val_accuracy: 0.8654
Epoch 7/10
253/253 [==============================] - 8s 32ms/step - loss: 0.1598 - accuracy: 0.9600 - val_loss: 0.7675 - val_accuracy: 0.8598

18-03-2022

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

In [ ]:
filepath_dir = {'yelp':'/content/drive/MyDrive/NLP/yelp_labelled.txt',
                'amazon':'/content/drive/MyDrive/NLP/amazon_cells_labelled.txt',
                'imdb':'/content/drive/MyDrive/NLP/imdb_labelled.txt'}
data_list = []
for source, filepath in filepath_dir.items():
  data = pd.read_csv(filepath, names=['sentence','label'], sep='\t')
  data['source'] = source
  data_list.append(data)
data = pd.concat(data_list)
data

sentence  label source
0                             Wow... Loved this place.      1   yelp
1                                   Crust is not good.      0   yelp
2            Not tasty and the texture was just nasty.      0   yelp
3    Stopped by during the late May bank holiday of...      1   yelp
4    The selection on the menu was great and so wer...      1   yelp
..                                                 ...    ...    ...
743  I just got bored watching Jessice Lange take h...      0   imdb
744  Unfortunately, any virtue in this film's produ...      0   imdb
745                   In a word, it is embarrassing.        0   imdb
746                               Exceptionally bad!        0   imdb
747  All in all its an insult to one's intelligence...      0   imdb

[2748 rows x 3 columns]

In [ ]:
from sklearn.model_selection import train_test_split
review = data['sentence'].values
label = data['label'].values
review_train, review_test, label_train, label_test = train_test_split(review, label, test_size=0.25, random_state=1000)

In [ ]:
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(review_train)
Xcnn_train = tokenizer.texts_to_sequences(review_train)
Xcnn_test = tokenizer.texts_to_sequences(review_test)
vocab_size = len(tokenizer.word_index)+1
print(review_train[1])
print(Xcnn_train[1])

There was a warm feeling with the service and I felt like their guest for a special treat.
[43, 10, 4, 607, 323, 15, 1, 47, 2, 3, 350, 37, 109, 1908, 12, 4, 279, 1236]


In [ ]:
from keras.preprocessing.sequence import pad_sequences
maxlen=100
Xcnn_train = pad_sequences(Xcnn_train, padding='post',maxlen = maxlen)
Xcnn_test = pad_sequences(Xcnn_test, padding='post',maxlen = maxlen)
print(Xcnn_train[0,:])

[ 278  295  212 1907   39  349    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0]


In [ ]:
from keras.models import Sequential
from keras import layers

In [ ]:
embedding_dim = 200
textcnnmodel = Sequential()
textcnnmodel.add(layers.Embedding(vocab_size, embedding_dim, input_length = maxlen))
textcnnmodel.add(layers.Conv1D(128, 5, activation='relu'))
textcnnmodel.add(layers.GlobalMaxPooling1D())
textcnnmodel.add(layers.Dense(10, activation='relu'))
textcnnmodel.add(layers.Dense(1, activation='sigmoid'))
textcnnmodel.compile(optimizer='adam',
                     loss='binary_crossentropy',
                     metrics = ['accuracy'])
textcnnmodel.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 100, 200)          920600    
                                                                 
 conv1d_3 (Conv1D)           (None, 96, 128)           128128    
                                                                 
 global_max_pooling1d_3 (Glo  (None, 128)              0         
 balMaxPooling1D)                                                
                                                                 
 dense_4 (Dense)             (None, 10)                1290      
                                                                 
 dense_5 (Dense)             (None, 1)                 11        
                                                                 
Total params: 1,050,029
Trainable params: 1,050,029
Non-trainable params: 0
____________________________________________

In [ ]:
textcnnmodel.fit(Xcnn_train, label_train,
                 epochs=10,
                 verbose=True,
                 validation_data=(Xcnn_test, label_test),
                 batch_size=10)
loss, accuracy = textcnnmodel.evaluate(Xcnn_train, label_train, verbose = True)
print("Training accuracy: ", accuracy)
loss, accuracy = textcnnmodel.evaluate(Xcnn_test, label_test, verbose = True)
print("Training accuracy: ", accuracy)

Epoch 1/10
207/207 [==============================] - 7s 34ms/step - loss: 0.0014 - accuracy: 1.0000 - val_loss: 0.5415 - val_accuracy: 0.8486
Epoch 2/10
207/207 [==============================] - 8s 40ms/step - loss: 7.8297e-04 - accuracy: 1.0000 - val_loss: 0.5661 - val_accuracy: 0.8443
Epoch 3/10
207/207 [==============================] - 8s 38ms/step - loss: 5.1158e-04 - accuracy: 1.0000 - val_loss: 0.5858 - val_accuracy: 0.8457
Epoch 4/10
207/207 [==============================] - 7s 34ms/step - loss: 3.7125e-04 - accuracy: 1.0000 - val_loss: 0.6035 - val_accuracy: 0.8413
Epoch 5/10
207/207 [==============================] - 7s 35ms/step - loss: 2.8236e-04 - accuracy: 1.0000 - val_loss: 0.6197 - val_accuracy: 0.8413
Epoch 6/10
207/207 [==============================] - 7s 35ms/step - loss: 2.2010e-04 - accuracy: 1.0000 - val_loss: 0.6333 - val_accuracy: 0.8428
Epoch 7/10
207/207 [==============================] - 7s 34ms/step - loss: 1.7500e-04 - accuracy: 1.0000 - val_loss: 0.647